- name: Configuring Redis
  hosts: redis
  become: yes
  tasks:
  - name: Disable redis
    ansible.builtin.command: dnf module disable redis -y

  - name: Enable redis
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Install redis
    ansible.builtin.dnf:
     name: redis
     state: present

  - name: Update IP adress in .conf file
    ansible.builtin.replace:  #This module replaces all occurences, ansible.builtin.lineinfile specific line
     path: /etc/redis/redis.conf
     regexp: '127.0.0.1'
     replace: '0.0.0.0'

  - name: Update 'protected mode' from yes to no in .conf file
    ansible.builtin.replace:
     path: /etc/redis/redis.conf
     regexp: 'protected-mode'
     replace: 'protected-mode no'

  - name: Start and enable redis
    ansible.builtin.service:
     name: redis
     state: started
     enabled: yes

  
